Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().


A = [[ 1  2  3]
 [ 2  1 -1]]

 B =[[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]

 C =[[1 2 3]
 [4 5 6]
 [7 8 9]]

 D = [[ 1]
 [ 4]
 [-3]]

In [4]:
import numpy as np
A = np.array([[1,2,3],[2,1,-1]])
B = np.array([[1,-2,0],[3,0,1],[4,5,6]])
C = np.array(range(1,10)).reshape(3,3)
D = np.array([[1],[4],[-3]])
print('A = {}'.format(A))
print('B = {}'.format(B))
print('C = {}'.format(C))
print('D = {}'.format(D))


A = [[ 1  2  3]
 [ 2  1 -1]]
B = [[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]
C = [[1 2 3]
 [4 5 6]
 [7 8 9]]
D = [[ 1]
 [ 4]
 [-3]]
