Podemos obter a transposta de uma matriz permutando as linhas pelas colunas de mesmo índice(ou seja, o que é linha se transforma em coluna e o que é coluna se transforma em linha). Obtenha a Matriz transposta das matrizes a seguir:

A =[[ 1 -3  2]
 
 [ 2  1 -3]
 
 [ 4 -3 -1]]

B =[[ 1  0  4]
 
 [-7  5  5]
 
 [25  9 11]]



Exemplo: Seja a matriz A definida a seguir, podemos obter sua transposta da seguinte forma:

A =[[ 1 -2]

 [ 7  4]

 [20 10]]

A° =[[ 1  7 20]
 
 [-2  4 10]]



In [2]:
import numpy as np

A = np.array([[1, -3 ,2], [2, 1, -3], [4, -3, -1]])
B = np.array([[1, 0, 4], [-7, 5, 5], [25, 9, 11]])


print(A.T,'Transposta de A')  #podemos ainda fazer: A.transpose()
print(B.transpose(),'Transposta de B')      

[[ 1  2  4]
 [-3  1 -3]
 [ 2 -3 -1]] Transposta de A
[[ 1 -7 25]
 [ 0  5  9]
 [ 4  5 11]] Transposta de B
