Encontre a inversa da matriz A:

A = [[ 4 -1  2 -2]

 [ 3 -1  0  0]

 [ 2  3  1  0]
 
 [ 0  7  1  1]]


Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.

In [2]:
import numpy as np
A = np.array([[4,-1,2,-2],[3,-1,0,0],[2,3,1,0],[0,7,1,1]])

invA = np.linalg.inv(A)
print(invA)

[[ -1.  -1.   4.  -2.]
 [ -3.  -4.  12.  -6.]
 [ 11.  14. -43.  22.]
 [ 10.  14. -41.  21.]]
