Obtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().

A = [[ 3  1  4]

 [10  7  5]

 [ 1  4  4]]

B = [[1. 0. 0.]

 [0. 1. 0.]
 
 [0. 0. 1.]]

C = [[ 5  0  0]

 [ 0 10  0]

 [ 0  0  2]]

D = [[ 3  0  0  0]

 [ 0  7  0  0]

 [ 0  0 11  0]

 [ 0  0  0  2]]

E = [[ 5  0 13 12]

 [ 1 -1 25  7]

 [ 6  2  1 20]
 
 [11  4  0 -9]]

In [7]:

import numpy as np

A = np.array([[3, 1, 4], [10, 7, 5], [1, 4, 4]])
B = np.eye(3)
C = np.diag([5,10,2])
D = np.diag([3, 7, 11, 2])
E = np.array([[5, 0, 13, 12], [1, -1, 25, 7], [6, 2, 1, 20], [11, 4, 0, -9]])

det_A = np.linalg.det(A).round()
det_B = np.linalg.det(B).round()
det_C = np.linalg.det(C).round()
det_D = np.linalg.det(D).round()
det_E = np.linalg.det(E).round()

print(det_A)
print()
print(det_B)
print()
print(det_C)
print()
print(det_D)
print()
print(det_E)

121.0

1.0

100.0

462.0

7081.0
