Encontre a inversa da matriz A:

A = [[ 7  0  0  0  0  0  0  0]

 [ 0  8  0  0  0  0  0  0]

 [ 0  0 11  0  0  0  0  0]

 [ 0  0  0  2  0  0  0  0]

 [ 0  0  0  0  4  0  0  0]

 [ 0  0  0  0  0  5  0  0]

 [ 0  0  0  0  0  0  1  0]
 
 [ 0  0  0  0  0  0  0  3]]

In [2]:
import numpy as np

A = np.diag([7, 8, 11, 2, 4, 5, 1, 3])

invA = np.linalg.inv(A)

print(invA)

[[0.14285714 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.125      0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.09090909 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.25       0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.2
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333]]
