Sejam as matrizes definidas a seguir, calculemos o que se pede na sequência.


A =[[ 1  2  3]
 
 [ 2  1 -1]]

B = [[-2  0  1]
 
 [ 3  0  1]]

C =[[-1]
 
 [ 2]
 
 [ 4]]


D = [ 2 -1]



A+B

A.C (multiplicação de matrizes)

B.C

C.D

D.A

D.B

-A

-D

2A+3B

Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.

In [6]:
import numpy as np

A = np.array([[1, 2, 3],[2, 1, -1]])
B = np.array([[-2, 0, 1], [3, 0 ,1]])
C = np.array([[-1], [2], [4]])
D = np.array([[2, -1]])

#1
print('A+B:',A+B)
print()
#2
print('A.C',A.dot(C))
print()
#3
print('B.C',B.dot(C))
print()
#4
print('C.D',C.dot(D))
print()
#5
print('D.A',D.dot(A))
print()
#6
print('D.B',D.dot(B))
print()
#7
print('-A',(-1)*(A))
print()
#8
print('-D',(-1)*D)
print()
#9
print('2A+3B:',2*A+3*B)
print()

A+B: [[-1  2  4]
 [ 5  1  0]]

A.C [[15]
 [-4]]

B.C [[6]
 [1]]

C.D [[-2  1]
 [ 4 -2]
 [ 8 -4]]

D.A [[0 3 7]]

D.B [[-7  0  1]]

-A [[-1 -2 -3]
 [-2 -1  1]]

-D [[-2  1]]

2A+3B: [[-4  4  9]
 [13  2  1]]

