Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().

In [3]:
import numpy as np
A = np.zeros(4)
print('A = {}'.format(A))
B = np.zeros(15)
print('B = {}'.format(B))
C = np.ones(25)
print('C = {}'.format(C))
D = np.eye(2)
print('D = {}'.format(D))
E = np.eye(3)
print('E = {}'.format(E))
F = np.eye(6)
print('F = {}'.format(F))

A = [0. 0. 0. 0.]
B = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
D = [[1. 0.]
 [0. 1.]]
E = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
F = [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
