Defina a matrizes triangulares abaixo utilizando o NumPy. Use os métodos np.triu() e np.tril().

A = [[1 2 3]

 [0 5 6]
 
 [0 0 9]]

B = [[1 0 0]

 [4 5 0]

 [7 8 9]]

C = [[100 101 102 103 104]

 [  0 106 107 108 109]

 [  0   0 112 113 114]

 [  0   0   0 118 119]

 [  0   0   0   0 124]]

In [4]:
import numpy as np

A = np.triu(np.arange(1,10).reshape(3,3),k=0)
B = np.tril(np.arange(1,10).reshape(3,3),k=0)
C = np.triu(np.arange(100,125).reshape(5,5))

print('A = {}'.format(A))
print()
print('B = {}'.format(B))
print()
print('C = {}'.format(C))


A = [[1 2 3]
 [0 5 6]
 [0 0 9]]

B = [[1 0 0]
 [4 5 0]
 [7 8 9]]

C = [[100 101 102 103 104]
 [  0 106 107 108 109]
 [  0   0 112 113 114]
 [  0   0   0 118 119]
 [  0   0   0   0 124]]
