Defina as matrizes abaixo utilizando o NumPy. Use os métodos np.diag() e np.array().

In [8]:
import numpy as np

A = np.diag([7, 1, -1])

print('A = {}'.format(A))
print()
B = np.diag([3]*4)
print('B = {}'.format(B))
print()

C = np.diag([-5, -4, -3, -2, -1])  #ou np.diag(range(-5, 0))
print('C = {}'.format(C))

A = [[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]]

B = [[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]

C = [[-5  0  0  0  0]
 [ 0 -4  0  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -1]]
