Gere uma distribuição normal aleatória de ordem 4 x 5. Armazene o resultado em uma variável.

In [4]:
from numpy import random 

data = random.normal(size = (4,5))
print(data)

[[-2.33288023 -2.24706831 -0.1895649   0.90299547 -0.32900052]
 [ 1.00696562 -0.84624519 -0.60566047  0.79034229 -2.45949566]
 [-0.02697255  1.41405772  0.11359908  1.02512226 -0.16489656]
 [-0.46638996  0.88705339 -0.31221497 -0.16867307  0.10569503]]
