Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:



array([-1,  4,  7,  9])



In [1]:
import numpy as np
array = np.array([-1, 4, 7, 9])


b) Use a função range() e obtenha:

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
array2 = np.array(range(1, 11))
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]


c)Use uma tupla como argumento e obtenha:



    
array([10, 11, 12, 13, 14])

In [3]:
tupla = (10, 11, 12, 13, 14)
array3 = np.array(tupla)
print(tupla)

(10, 11, 12, 13, 14)


d) Use a função range() e obtenha:



    
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [4]:
array4 = np.array(range(1990, 2021,5))
print(array4)

[1990 1995 2000 2005 2010 2015 2020]


e) Use a função range() e obtenha:



array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

In [5]:
array4 = np.array(range(2020,1899,-5))
print(array4)

[2020 2015 2010 2005 2000 1995 1990 1985 1980 1975 1970 1965 1960 1955
 1950 1945 1940 1935 1930 1925 1920 1915 1910 1905 1900]


f) Obtenha:



array(100)

In [6]:
array5 = np.array(100)
print(array5)

100
