A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

a)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1]:
import numpy as np
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


b)



array([[1., 1., 1., 1.],

       [1., 1., 1., 1.],

       [1., 1., 1., 1.],
       
       [1., 1., 1., 1.]])

In [2]:
array2 = np.ones((4, 4))
print(array2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


c)



array([[1, 1],

       [1, 1],
       
       [1, 1]])

In [3]:
array3 = np.ones((3, 3))