A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

a)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
import numpy as np
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


b)



array([[0., 0.],

       [0., 0.]])  

In [2]:
array2 = np.zeros(shape = (2, 2))
print(array2)

[[0. 0.]
 [0. 0.]]


c)



array([[0., 0., 0., 0., 0., 0.],

       [0., 0., 0., 0., 0., 0.],

       [0., 0., 0., 0., 0., 0.],
       
       [0., 0., 0., 0., 0., 0.]])

In [3]:
array3 = np.zeros(shape = (4, 6))
print(array3)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
