Crie os arrays a seguir:

   

a)
array([[10],

[15],

[20],

[25],

[30],

[35],

[40],

[45]])

In [1]:
import numpy as np
array = np.array(range(10, 46, 5)).reshape(-1,1)
print(array)


[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]


b)



array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

In [2]:
array2 = np.array(range(-50, -4, 5))
print(array2)

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]


c)



array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],

       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],

       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],

       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
       

Dica: use np.arange() ou np.array(range()).

In [3]:
array3 = np.arange(50,150,2).reshape((5,10))
print(array3)

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]
