Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

a)



array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [3]:
import numpy as np
a = np.full(shape=(10),fill_value = 5,dtype = float)  
#ou: 5*np.ones(10)
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


b)



array([[-5., -5., -5., -5.],

       [-5., -5., -5., -5.],

       [-5., -5., -5., -5.],
       
       [-5., -5., -5., -5.]])

In [5]:
b = np.full(shape =(4, 4), fill_value= -5, dtype=float) #ou: (-5)*np.ones(shape=(4,4))
print(b)

[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]


c)



array([[3, 3, 3],

       [3, 3, 3],
       
       [3, 3, 3]])

In [6]:
c = np.full(shape= (3, 3), fill_value= 3, dtype= int) #ou: (3)*np.ones(shape = (3,3),dtype=int)
print(c)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


d)



array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],

       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])


Dica: outra possibilidade seria obter os arrays com uma operação diferente, a partir da multiplicação de uma matriz preenchida com número 1 por um determinado valor.

In [7]:
d = np.full(shape = (10,10), fill_value= 50, dtype = int) #ou: (50)*np.ones(shape = (10,10), dtype = int)
print(d)

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]
