Use a função np.diag() para construir o array a seguir:



array([[ 5,  0,  0,  0,  0,  0],

       [ 0, 10,  0,  0,  0,  0],

       [ 0,  0, 15,  0,  0,  0],

       [ 0,  0,  0, 20,  0,  0],

       [ 0,  0,  0,  0, 25,  0],
       
       [ 0,  0,  0,  0,  0, 30]])

In [1]:
import numpy as np

a = np.diag(range(5,31,5))
print(a)

[[ 5  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 30]]
