Use a função np.eye() (ou ainda np.identity()) para obter o array seguir.



array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],

       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],

       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],

       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],

       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],

       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],

       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],

       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],

       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


Dica: essa matriz é definida como matriz identidade, neste caso de ordem 10, e assume grande relevância em diversos cálculos computacionais, como veremos mais adiante.

In [3]:
import numpy as np

a = np.eye(10)  #ou: np.identity(n = 10)
print (a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
