A partir da matriz definida abaixo obtenha:  



import numpy as np
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)

In [2]:
import numpy as np
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
print(matriz)

[[18 38 66]
 [71 33 80]
 [47 37 16]
 [62  5 26]
 [38 94 46]]


 a) soma total dos elementos;
 

In [5]:
print('Soma total dos elementos: ', matriz.sum())

Soma total dos elementos:  677


b) soma das linhas ;

In [4]:
print('Soma das linhas: ', matriz.sum(axis = 1))
    

Soma das linhas:  [122 184 100  93 178]


c) soma das colunas.

In [6]:
print('Soma das colunas: ', matriz.sum(axis = 0))

Soma das colunas:  [236 207 234]
